// mobile/src/app/(app)/challenge/[id].tsx
import { getChallenge, getChallengeLeaderboard, startChallenge } from "@/api/challenges";
import { Board } from "@/components/Board";
import { Button } from "@/components/Button";
import { Icon } from "@/components/Icon";
import { Screen } from "@/components/Screen";
import {
  CHALLENGE_RUN_STATUS,
  CHALLENGE_TYPES,
  formatChallengeElapsedMs,
  formatChallengeOverview,
  formatChallengeRankValue,
  formatChallengeTypeLabel
} from "@/game/challenges";
import { getInkColor } from "@/theme/themes";
import { useSessionStore } from "@/stores/session";
import { useThemeStore } from "@/stores/theme";
import { useQuery } from "@tanstack/react-query";
import { Link, useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

function formatDate(dateStr?: string | null) {
  if (!dateStr) return "";
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d, 18)).toLocaleDateString(undefined, {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC"
  });
}

export default function ChallengeDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const challengeId = String(id);
  const theme = useThemeStore((s) => s.theme);
  const user = useSessionStore((s) => s.user);
  const router = useRouter();
  const [starting, setStarting] = useState(false);
  const [showLeaders, setShowLeaders] = useState(false);
  const { data, isLoading } = useQuery({
    queryKey: ["challenge", challengeId],
    queryFn: () => getChallenge(challengeId),
    enabled: Boolean(challengeId)
  });
  const leaders = useQuery({
    queryKey: ["challenge-leaderboard", challengeId],
    queryFn: () => getChallengeLeaderboard(challengeId),
    enabled: Boolean(challengeId)
  });

  const boardInk = getInkColor(theme.boardBackground, theme);
  const challenge = data?.challenge;
  const previewBoard = !data?.locked && Array.isArray(challenge?.params.board) ? (challenge?.params.board as number[][]) : null;
  const stats = data?.userStats;

  const begin = async () => {
    if (!user?.isPro || starting) return;
    setStarting(true);
    try {
      const started = await startChallenge(challengeId);
      router.push({ pathname: "/(app)/challenge/[id]/play", params: { id: challengeId, runId: started.runId } });
    } finally {
      setStarting(false);
    }
  };

  if (isLoading) return <Screen title="Challenge"><ActivityIndicator /></Screen>;
  if (!challenge) return <Screen title="Challenge"><Text style={{ color: theme.textLight }}>Challenge not found.</Text></Screen>;

  return (
    <Screen>
      <Link href="/(app)/(tabs)/challenges" asChild>
        <Pressable style={styles.back}>
          <Icon name="arrowLeft" size={16} color={theme.primary} />
          <Text style={{ color: theme.primary, fontWeight: "700" }}>Calendar</Text>
        </Pressable>
      </Link>

      <Text style={[styles.kicker, { color: theme.textLight }]}>
        {data?.isToday || data?.date === undefined ? "Today's challenge" : "Daily challenge"}
        {data?.date ? ` · ${formatDate(data.date)}` : ""}
      </Text>
      <Text style={[styles.title, { color: theme.primary }]}>{challenge.title}</Text>

      {data?.locked ? (
        <View style={[styles.card, { backgroundColor: theme.boardBackground }]}>
          <Text style={{ color: boardInk, textAlign: "center" }}>
            Past daily challenges are a Pro feature — same archive pattern as game history.
          </Text>
          <Link href={user ? "/(app)/pro" : "/(auth)/login"} asChild>
            <Button>{user ? "Upgrade to Pro" : "Log in"}</Button>
          </Link>
        </View>
      ) : (
        <>
          <Text style={{ color: theme.textLight }}>
            {challenge.difficulty} · {formatChallengeTypeLabel(challenge.type)}
          </Text>
          <Text style={{ color: theme.text ?? theme.textLight, fontSize: 16 }}>
            {formatChallengeOverview(challenge)}
          </Text>

          {previewBoard ? (
            <View>
              <Text style={[styles.kicker, { color: theme.textLight }]}>Starting board</Text>
              <Board board={previewBoard} compact />
            </View>
          ) : null}

          {stats ? (
            <Text style={{ color: theme.textLight }}>
              {stats.bestStatus === CHALLENGE_RUN_STATUS.WON
                ? `You've cleared this challenge ${stats.wins ?? 0} time${stats.wins === 1 ? "" : "s"} (${stats.attempts ?? 0} attempt${stats.attempts === 1 ? "" : "s"}).${
                    challenge.type === CHALLENGE_TYPES.RECOVERY && stats.bestMoveCount != null
                      ? ` Best: ${stats.bestMoveCount} moves.`
                      : challenge.type === CHALLENGE_TYPES.TIME && stats.bestElapsedMs != null
                        ? ` Best time: ${formatChallengeElapsedMs(stats.bestElapsedMs)}.`
                        : ""
                  }`
                : (stats.attempts ?? 0) > 0
                  ? `${stats.attempts} attempt${stats.attempts === 1 ? "" : "s"} so far — keep going!`
                  : "No attempts yet."}
            </Text>
          ) : (
            <Text style={{ color: theme.textLight }}>No attempts yet.</Text>
          )}

          {user?.isPro ? (
            <Button disabled={starting} onPress={() => void begin()}>
              {starting ? "Starting…" : "Start Challenge"}
            </Button>
          ) : (
            <View style={[styles.card, { backgroundColor: theme.boardBackground }]}>
              <Text style={{ color: boardInk, textAlign: "center" }}>
                {user ? "Upgrade to Pro to play daily challenges." : "Log in and upgrade to Pro to play daily challenges."}
              </Text>
              <Link href={user ? "/(app)/pro" : "/(auth)/login"} asChild>
                <Button>{user ? "Upgrade to Pro" : "Log in"}</Button>
              </Link>
            </View>
          )}

          <Pressable
            onPress={() => setShowLeaders((open) => !open)}
            style={[styles.leaderboard, { backgroundColor: theme.boardBackground }]}
          >
            <View style={[styles.trophy, { backgroundColor: theme.secondary }]}>
              <Icon name="trophy" color={theme.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={[styles.kicker, { color: boardInk }]}>Global leaderboard</Text>
              <Text style={{ color: boardInk, fontWeight: "700" }}>
                {leaders.data?.entryCount
                  ? `${leaders.data.entryCount} clear${leaders.data.entryCount === 1 ? "" : "s"} — tap to view`
                  : "No clears yet — be the first"}
              </Text>
            </View>
            <Icon name={showLeaders ? "close" : "chevronRight"} color={boardInk} />
          </Pressable>
          {showLeaders
            ? (leaders.data?.entries?.length
                ? leaders.data.entries.map((entry, i) => (
                    <Text key={`${entry.username}-${i}`} style={{ color: theme.textLight }}>
                      {entry.rank ?? i + 1}. {entry.displayName || entry.username || "Player"} ·{" "}
                      {formatChallengeRankValue(challenge.type, Number(entry.score ?? entry.value ?? 0))}
                    </Text>
                  ))
                : <Text style={{ color: theme.textLight }}>No entries yet.</Text>)
            : null}
        </>
      )}
    </Screen>
  );
}

const styles = StyleSheet.create({
  back: { flexDirection: "row", alignItems: "center", gap: 4 },
  kicker: { fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  title: { fontSize: 32, fontWeight: "900" },
  card: { borderRadius: 12, padding: 16, gap: 12 },
  leaderboard: { borderRadius: 12, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  trophy: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }
});

// src/routes/challenges/[id]/+page.svelte
<script>
	import { enhance } from "$app/forms";
	import { page } from "$app/state";
	import { getInkColor } from "$lib/assets/themes.js";
	import BoardPreview from "$lib/components/BoardPreview.svelte";
	import {
		CHALLENGE_RUN_STATUS,
		CHALLENGE_TYPES,
		formatChallengeElapsedMs,
		formatChallengeRankValue,
		formatChallengeTypeLabel,
	} from "$lib/challenges.js";
	import { Button } from "$lib/components/ui/button/index.js";
	import { CrownIcon, ArrowLeftIcon, ChevronRightIcon, TrophyIcon } from "@lucide/svelte";

	let { data } = $props();

	let starting = $state(false);

	const theme = $derived(page.data.theme);
	// Readable ink for board-colored surfaces (locked banner, leaderboard link)
	const boardInk = $derived(theme ? getInkColor(theme.boardBackground, theme) : "#f9f6f2");

	const challenge = $derived(data.challenge);
	const typeLabel = $derived(formatChallengeTypeLabel(challenge.type));

	const previewBoard = $derived(
		!data.locked && "board" in challenge.params && Array.isArray(challenge.params.board)
			? challenge.params.board
			: null
	);

	const leaderboardHref = $derived(`/challenges/${challenge.id}/leaderboard`);

	function onStart() {
		starting = true;
		return async ({ update }) => {
			await update();
			starting = false;
		};
	}

	/**
	 * @param {string | null | undefined} dateStr
	 */
	function formatDate(dateStr) {
		if (!dateStr) return "";
		const [y, m, d] = dateStr.split("-").map(Number);
		return new Date(Date.UTC(y, m - 1, d, 18)).toLocaleDateString(undefined, {
			weekday: "long",
			month: "long",
			day: "numeric",
			year: "numeric",
			timeZone: "UTC",
		});
	}
</script>

<svelte:head>
	<title>{challenge.title} - Challenges - 4096</title>
</svelte:head>

<main class="mx-auto w-full max-w-lg px-4 pt-8 pb-28 text-foreground">
	<a
		href="/challenges"
		class="mb-4 inline-flex items-center gap-1 text-sm text-primary hover:underline"
	>
		<ArrowLeftIcon size={16} />
		Calendar
	</a>

	<p class="mb-1 text-xs font-bold tracking-wide text-muted-foreground uppercase">
		{#if data.isToday}
			Today's challenge
		{:else}
			Daily challenge
		{/if}
		{#if data.dateStr}
			· {formatDate(data.dateStr)}
		{/if}
	</p>
	<h1 class="text-3xl font-bold text-primary">{challenge.title}</h1>

	{#if data.locked}
		<div class="mt-6 rounded-lg p-4 text-center" style:background-color={theme?.boardBackground}>
			<p class="mb-3 text-sm" style:color={boardInk}>
				Past daily challenges are a Pro feature — same archive pattern as game history.
			</p>
			{#if data.user}
				<Button href="/stripe" class="justify-center gap-2">
					<CrownIcon size={20} />
					Upgrade to Pro
				</Button>
			{:else}
				<Button href="/login?redirectTo=/challenges/{challenge.id}" class="justify-center">
					Log in
				</Button>
			{/if}
		</div>
	{:else}
		<p class="mb-1 text-sm text-muted-foreground">{challenge.difficulty} · {typeLabel}</p>
		<p class="mb-6 text-base">{data.overview}</p>

		{#if previewBoard && theme}
			<div class="mb-6">
				<p class="mb-2 text-xs font-bold tracking-wide text-muted-foreground uppercase">
					Starting board
				</p>
				<BoardPreview {theme} board={previewBoard} />
			</div>
		{/if}

		{#if data.stats}
			<p class="mb-4 text-sm text-muted-foreground">
				{#if data.stats.bestStatus === CHALLENGE_RUN_STATUS.WON}
					You've cleared this challenge {data.stats.wins} time{data.stats.wins === 1 ? "" : "s"}
					({data.stats.attempts} attempt{data.stats.attempts === 1 ? "" : "s"}).
					{#if challenge.type === CHALLENGE_TYPES.RECOVERY && data.stats.bestMoveCount != null}
						Best: {data.stats.bestMoveCount} move{data.stats.bestMoveCount === 1 ? "" : "s"}.
					{:else if challenge.type === CHALLENGE_TYPES.TIME && data.stats.bestElapsedMs != null}
						Best time: {formatChallengeElapsedMs(data.stats.bestElapsedMs)}.
					{/if}
				{:else if data.stats.attempts > 0}
					{data.stats.attempts} attempt{data.stats.attempts === 1 ? "" : "s"} so far — keep going!
				{:else}
					No attempts yet.
				{/if}
			</p>
		{/if}

		{#if data.isPro}
			<form method="POST" action="?/start" use:enhance={onStart}>
				<Button type="submit" class="w-full justify-center" disabled={starting}>
					{starting ? "Starting…" : "Start Challenge"}
				</Button>
			</form>
		{:else}
			<div class="rounded-lg p-4 text-center" style:background-color={theme?.boardBackground}>
				<p class="mb-3 text-sm" style:color={boardInk}>
					{#if data.user}
						Upgrade to Pro to play daily challenges.
					{:else}
						Log in and upgrade to Pro to play daily challenges.
					{/if}
				</p>
				{#if data.user}
					<Button href="/stripe" class="justify-center gap-2">
						<CrownIcon size={20} />
						Upgrade to Pro
					</Button>
				{:else}
					<Button href="/login?redirectTo=/challenges/{challenge.id}" class="justify-center">
						Log in
					</Button>
				{/if}
			</div>
		{/if}

		<a
			href={leaderboardHref}
			class="mt-6 flex items-center gap-3 rounded-lg px-4 py-3 transition-colors hover:brightness-95"
			style:background-color={theme?.boardBackground}
			style:color={boardInk}
		>
			<span
				class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-secondary text-primary"
			>
				<TrophyIcon size={20} />
			</span>
			<span class="min-w-0 flex-1">
				<span class="block text-sm font-bold tracking-wide uppercase opacity-80"
					>Global leaderboard</span
				>
				{#if data.userRank != null && data.userBestScore != null}
					<span class="block text-base font-semibold">
						Your rank: #{data.userRank}
						{#if data.entryCount > 0}
							<span class="font-normal opacity-80">of {data.entryCount}</span>
						{/if}
						<span class="font-normal opacity-80">
							· {formatChallengeRankValue(challenge.type, data.userBestScore)}
							{#if challenge.type === CHALLENGE_TYPES.RECOVERY}
								moves
							{/if}
						</span>
					</span>
				{:else if data.entryCount > 0}
					<span class="block text-base font-semibold">
						{data.entryCount} clear{data.entryCount === 1 ? "" : "s"} — tap to view
					</span>
				{:else}
					<span class="block text-base font-semibold">No clears yet — be the first</span>
				{/if}
			</span>
			<ChevronRightIcon size={20} class="shrink-0 opacity-70" />
		</a>
	{/if}
</main>
