// mobile/src/app/(app)/challenge/[id]/play.tsx
import { completeChallenge, getChallenge, startChallenge } from "@/api/challenges";
import { Board } from "@/components/Board";
import { Button } from "@/components/Button";
import { GameOverlay } from "@/components/GameOverlay";
import { Screen } from "@/components/Screen";
import {
  CHALLENGE_TYPES,
  challengeCompleteScore,
  countFilledCells,
  evaluateChallenge,
  formatChallengeElapsedMs,
  formatChallengeObjective
} from "@/game/challenges";
import { Game } from "@/game/Game";
import { useAnimatedBoard } from "@/hooks/useAnimatedBoard";
import { useBoardSwipe } from "@/hooks/useBoardSwipe";
import { formatCountdown } from "@/lib/format";
import { useSessionStore } from "@/stores/session";
import { useThemeStore } from "@/stores/theme";
import { getInkColor } from "@/theme/themes";
import type { GameEvent } from "@/types";
import { useQuery } from "@tanstack/react-query";
import { Link, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { GestureDetector } from "react-native-gesture-handler";

const GAME_OVER_DELAY_MS = 1200;

function createChallengeGame(challenge: { type: string; params: Record<string, unknown> }) {
  const seed = Number(challenge.params.seed ?? undefined);
  const winTile = challenge.type === CHALLENGE_TYPES.RECOVERY ? Number(challenge.params.winTile ?? 4096) : undefined;
  if (Array.isArray(challenge.params.board)) {
    return new Game({
      seed,
      winTile,
      initialState: {
        board: (challenge.params.board as number[][]).map((row) => [...row]),
        score: 0,
        seed,
        moveCount: 0,
        undoCooldownRemaining: 0
      }
    });
  }
  return new Game({ seed, winTile });
}

export default function ChallengePlayScreen() {
  const { id, runId: runIdParam } = useLocalSearchParams<{ id: string; runId?: string }>();
  const challengeId = String(id);
  const user = useSessionStore((s) => s.user);
  const theme = useThemeStore((s) => s.theme);
  const router = useRouter();
  const [game, setGame] = useState<Game | null>(null);
  const [runId, setRunId] = useState<string | null>(runIdParam ? String(runIdParam) : null);
  const [startMs, setStartMs] = useState(0);
  const [remainingMs, setRemainingMs] = useState(0);
  const [result, setResult] = useState<"won" | "lost" | null>(null);
  const [pendingLoss, setPendingLoss] = useState(false);
  const [finishedElapsedMs, setFinishedElapsedMs] = useState<number | null>(null);
  const [version, setVersion] = useState(0);
  const completing = useRef(false);
  const { data, isLoading } = useQuery({
    queryKey: ["challenge", challengeId],
    queryFn: () => getChallenge(challengeId),
    enabled: Boolean(challengeId)
  });
  const { tiles, playEvents } = useAnimatedBoard(game);
  const challenge = data?.challenge;
  const isTime = challenge?.type === CHALLENGE_TYPES.TIME;
  const isRecovery = challenge?.type === CHALLENGE_TYPES.RECOVERY;
  const boardInk = getInkColor(theme.boardBackground, theme);
  const urgentInk = theme.destructive ?? "#b91c1c";

  const startRun = useCallback(async (reuseRunId?: string | null) => {
    if (!user?.isPro || !challenge) return;
    const started = reuseRunId ? { runId: reuseRunId, challenge } : await startChallenge(challengeId);
    setRunId(started.runId);
    setStartMs(Date.now());
    setResult(null);
    setPendingLoss(false);
    setFinishedElapsedMs(null);
    completing.current = false;
    const next = createChallengeGame(started.challenge);
    setGame(next);
    if (started.challenge.type === CHALLENGE_TYPES.TIME) {
      setRemainingMs(Number(started.challenge.params.durationSec ?? 0) * 1000);
    }
  }, [challenge, challengeId, user?.isPro]);

  const bootstrapped = useRef(false);
  useEffect(() => {
    if (!challenge || !user?.isPro || bootstrapped.current) return;
    bootstrapped.current = true;
    void startRun(runIdParam ? String(runIdParam) : null);
  }, [challenge, runIdParam, startRun, user?.isPro]);

  const finish = useCallback(
    (status: "won" | "lost") => {
      if (!game || !challenge || !runId || completing.current) return;
      completing.current = true;
      const elapsedMs = finishedElapsedMs ?? Math.max(0, Date.now() - startMs);
      setFinishedElapsedMs(elapsedMs);
      setResult(status);
      setPendingLoss(false);
      void completeChallenge(challengeId, {
        runId,
        status,
        score: challengeCompleteScore(challenge, { score: game.score, moveCount: game.moveCount, elapsedMs }),
        metrics: {
          moveCount: game.moveCount,
          filledCells: countFilledCells(game.board),
          elapsedMs,
          mergeScore: game.score
        }
      }).catch(() => undefined);
    },
    [challenge, challengeId, finishedElapsedMs, game, runId, startMs]
  );

  const checkOutcome = useCallback(() => {
    if (!game || !challenge || result || pendingLoss) return;
    const elapsedMs = Date.now() - startMs;
    const outcome = evaluateChallenge(challenge, {
      board: game.board,
      score: game.score,
      gameOver: game.gameOver,
      won: game.won,
      elapsedMs
    });
    if (outcome === "won") finish("won");
    else if (outcome === "lost") {
      setFinishedElapsedMs(elapsedMs);
      setPendingLoss(true);
      setTimeout(() => finish("lost"), GAME_OVER_DELAY_MS);
    }
  }, [challenge, finish, game, pendingLoss, result, startMs]);

  useEffect(() => {
    if (!isTime || !challenge || result) return;
    const durationMs = Number(challenge.params.durationSec ?? 0) * 1000;
    const timer = setInterval(() => {
      setRemainingMs(Math.max(0, durationMs - (Date.now() - startMs)));
      checkOutcome();
    }, 200);
    return () => clearInterval(timer);
  }, [challenge, checkOutcome, isTime, result, startMs]);

  const commit = useCallback(
    (direction: number) => {
      if (!game || !challenge || result || pendingLoss) return;
      const events = game.moveTiles(direction) as GameEvent[];
      if (!events.length) return;
      playEvents(events);
      setVersion((n) => n + 1);
      checkOutcome();
    },
    [challenge, checkOutcome, game, pendingLoss, playEvents, result]
  );

  const swipe = useBoardSwipe(commit, Boolean(game) && !result);

  const reset = async () => {
    setRunId(null);
    setGame(null);
    await startRun(null);
  };

  if (isLoading) return <Screen title="Challenge"><ActivityIndicator /></Screen>;
  if (!user?.isPro) {
    return (
      <Screen title="Challenge" subtitle="Challenge play is a Pro feature.">
        <Link href="/(app)/pro" asChild>
          <Button>Upgrade to Pro</Button>
        </Link>
      </Screen>
    );
  }
  if (!challenge) return <Screen title="Challenge"><Text style={{ color: theme.textLight }}>Challenge not found.</Text></Screen>;

  const winTile = isRecovery ? Number(challenge.params.winTile ?? 4096) : null;

  return (
    <Screen scroll={false}>
      <GestureDetector gesture={swipe}>
        <View style={styles.play} key={version}>
          <View style={styles.header}>
            <View style={{ flex: 1 }}>
              <Text style={[styles.kicker, { color: theme.textLight }]}>Daily Challenge</Text>
              <Text style={[styles.title, { color: theme.primary }]}>{challenge.title}</Text>
              <Text style={{ color: theme.textLight }}>{formatChallengeObjective(challenge)}</Text>
            </View>
            <View style={styles.stats}>
              {isRecovery ? (
                <>
                  <View style={[styles.stat, { backgroundColor: theme.boardBackground }]}>
                    <Text style={[styles.statLabel, { color: boardInk }]}>Moves</Text>
                    <Text style={[styles.statValue, { color: boardInk }]}>{game?.moveCount ?? 0}</Text>
                  </View>
                  {winTile ? (
                    <View style={[styles.stat, { backgroundColor: theme.boardBackground }]}>
                      <Text style={[styles.statLabel, { color: boardInk }]}>Goal</Text>
                      <Text style={[styles.statValue, { color: boardInk }]}>{winTile}</Text>
                    </View>
                  ) : null}
                </>
              ) : (
                <>
                  <View style={[styles.stat, { backgroundColor: theme.boardBackground }]}>
                    <Text style={[styles.statLabel, { color: boardInk }]}>Score</Text>
                    <Text style={[styles.statValue, { color: boardInk }]}>{game?.score.toLocaleString() ?? "—"}</Text>
                  </View>
                  {isTime ? (
                    <View style={[styles.stat, { backgroundColor: theme.boardBackground }]}>
                      <Text style={[styles.statLabel, { color: remainingMs <= 10000 ? urgentInk : boardInk }]}>Time</Text>
                      <Text style={[styles.statValue, { color: remainingMs <= 10000 ? urgentInk : boardInk }]}>
                        {formatCountdown(remainingMs)}
                      </Text>
                    </View>
                  ) : null}
                </>
              )}
            </View>
          </View>

          {game ? <Board board={game.board} tiles={tiles} /> : <ActivityIndicator />}

          {pendingLoss ? (
            <Text style={{ color: urgentInk, textAlign: "center", fontWeight: "700" }}>
              {game?.gameOver ? "No moves left…" : isTime ? "Time's up…" : "Challenge over…"}
            </Text>
          ) : null}

          <View style={styles.actions}>
            <Button
              variant="secondary"
              disabled={Boolean(result) || pendingLoss}
              onPress={() => void reset()}
            >
              Reset
            </Button>
            <Button variant="outline" onPress={() => router.replace(`/(app)/challenge/${challengeId}`)}>
              Abandon & back
            </Button>
          </View>
        </View>
      </GestureDetector>

      <GameOverlay
        open={Boolean(result)}
        title={result === "won" ? "Challenge Cleared!" : "Challenge Failed"}
        subtitle={
          result === "won"
            ? `Nice work — ${formatChallengeObjective(challenge).toLowerCase()}.`
            : isTime
              ? "Time's up (or game over) before reaching the target score."
              : "Game over before the objective was met."
        }
        stats={[
          isRecovery
            ? { label: "Moves", value: (game?.moveCount ?? 0).toLocaleString() }
            : isTime
              ? { label: "Time", value: formatChallengeElapsedMs(finishedElapsedMs) }
              : { label: "Score", value: (game?.score ?? 0).toLocaleString() },
          { label: isRecovery ? "Score" : "Moves", value: isRecovery ? (game?.score ?? 0).toLocaleString() : (game?.moveCount ?? 0).toLocaleString() },
          { label: isTime ? "Score" : "Time", value: isTime ? (game?.score ?? 0).toLocaleString() : formatChallengeElapsedMs(finishedElapsedMs) }
        ]}
      >
        <Button onPress={() => void reset()}>Retry</Button>
        <Button variant="secondary" onPress={() => router.replace("/(app)/(tabs)/challenges")}>
          Calendar
        </Button>
      </GameOverlay>
    </Screen>
  );
}

const styles = StyleSheet.create({
  play: { flex: 1, gap: 12 },
  header: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  kicker: { fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  title: { fontSize: 24, fontWeight: "900" },
  stats: { gap: 8 },
  stat: { minWidth: 72, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, alignItems: "center" },
  statLabel: { fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  statValue: { fontSize: 16, fontWeight: "800" },
  actions: { flexDirection: "row", gap: 10 }
});

// src/routes/challenges/[id]/play/+page.svelte
<script>
	import { applyAction, enhance } from "$app/forms";
	import { goto } from "$app/navigation";
	import { untrack } from "svelte";
	import { page } from "$app/state";
	import { Game } from "$lib/game.svelte.js";
	import { DIRECTIONS } from "$lib/constants.js";
	import { createSwipeHandlers } from "$lib/swipe.js";
	import {
		CHALLENGE_RUN_STATUS,
		CHALLENGE_TYPES,
		countFilledCells,
		evaluateChallenge,
		formatChallengeElapsedMs,
	} from "$lib/challenges.js";
	import { Button } from "$lib/components/ui/button/index.js";
	import GameStats from "$lib/components/GameStats.svelte";
	import AnimatedBoard from "../../../game/components/AnimatedBoard.svelte";

	let { data } = $props();

	/** @type {Game | null} */
	let game = $state(null);
	let result = $state(/** @type {'won' | 'lost' | null} */ (null));
	let remainingMs = $state(0);
	/** Elapsed ms captured when the run finishes. */
	let finishedElapsedMs = $state(/** @type {number | null} */ (null));
	let submitting = $state(false);
	let retrying = $state(false);

	/** @type {import("$lib/types").GameEvent[]} */
	let pendingEvents = $state([]);

	/** @type {HTMLFormElement | null} */
	let completeForm = $state(null);

	const challenge = $derived(data.challenge);
	const isTime = $derived(challenge.type === CHALLENGE_TYPES.TIME);
	const isRecovery = $derived(challenge.type === CHALLENGE_TYPES.RECOVERY);

	const winTile = $derived(
		isRecovery && "winTile" in challenge.params ? challenge.params.winTile : null
	);

	/**
	 * Build a Game from challenge params.
	 * @returns {Game}
	 */
	function createChallengeGame() {
		const params = challenge.params;
		const seed = "seed" in params ? params.seed : undefined;
		const winTile =
			challenge.type === CHALLENGE_TYPES.RECOVERY && "winTile" in params
				? params.winTile
				: undefined;

		if ("board" in params && params.board) {
			return new Game({
				seed,
				winTile,
				initialState: {
					board: params.board.map((row) => [...row]),
					score: 0,
					seed,
					moveCount: 0,
					undoCooldownRemaining: 0,
				},
			});
		}

		return new Game({ seed, winTile });
	}

	/**
	 * @param {number} startedOn
	 */
	function initGame(startedOn) {
		pendingEvents = [];
		game = createChallengeGame();
		result = null;
		finishedElapsedMs = null;
		submitting = false;
		retrying = false;

		if (isTime && "durationSec" in challenge.params) {
			const durationMs = challenge.params.durationSec * 1000;
			remainingMs = Math.max(0, durationMs - (Date.now() - startedOn));
		}
	}

	/**
	 * @param {number} ms
	 */
	function formatTime(ms) {
		const totalSec = Math.max(0, Math.ceil(ms / 1000));
		const m = Math.floor(totalSec / 60);
		const s = totalSec % 60;
		return `${m}:${s.toString().padStart(2, "0")}`;
	}

	/**
	 * @param {'won' | 'lost'} status
	 */
	function finish(status) {
		if (result || submitting || data.run.status !== CHALLENGE_RUN_STATUS.IN_PROGRESS) return;
		result = status;
		finishedElapsedMs = Math.max(0, Date.now() - data.run.startedOn);
		submitting = true;
		queueMicrotask(() => completeForm?.requestSubmit());
	}

	/**
	 * @param {number} [startedOn]
	 */
	function checkOutcome(startedOn = data.run.startedOn) {
		if (!game || result) return;

		const elapsedMs = isTime ? Date.now() - startedOn : undefined;
		const outcome = evaluateChallenge(challenge, {
			board: game.board,
			score: game.score,
			gameOver: game.gameOver,
			won: game.won,
			elapsedMs,
		});

		if (outcome === "won" || outcome === "lost") {
			finish(outcome);
		}
	}

	/**
	 * @returns {import("$lib/types").GameEvent | undefined}
	 */
	function popEvent() {
		return pendingEvents.shift();
	}

	/**
	 * @param {number} direction
	 */
	function handleMove(direction) {
		if (!game || result) return;
		const events = game.moveTiles(direction);
		if (events.length > 0) {
			pendingEvents.push(...events);
			checkOutcome();
		}
	}

	/**
	 * @param {KeyboardEvent} event
	 */
	function handleKeydown(event) {
		switch (event.key) {
			case "ArrowLeft":
				event.preventDefault();
				handleMove(DIRECTIONS.LEFT);
				break;
			case "ArrowRight":
				event.preventDefault();
				handleMove(DIRECTIONS.RIGHT);
				break;
			case "ArrowUp":
				event.preventDefault();
				handleMove(DIRECTIONS.UP);
				break;
			case "ArrowDown":
				event.preventDefault();
				handleMove(DIRECTIONS.DOWN);
				break;
		}
	}

	const { handleTouchStart, handleTouchEnd, handleTouchMove } = createSwipeHandlers(handleMove);

	// Re-init when Retry starts a new run on the same play route (no remount).
	$effect(() => {
		const runId = data.run.id;
		const status = data.run.status;
		const startedOn = data.run.startedOn;
		void runId;

		if (status !== CHALLENGE_RUN_STATUS.IN_PROGRESS) {
			result = status === CHALLENGE_RUN_STATUS.WON ? "won" : "lost";
			const metrics = data.run.metrics;
			if (metrics && typeof metrics === "object") {
				const elapsed = /** @type {{ elapsedMs?: unknown }} */ (metrics).elapsedMs;
				finishedElapsedMs =
					typeof elapsed === "number" && Number.isFinite(elapsed) ? elapsed : null;
			}
			return;
		}

		const timed = untrack(() => isTime);
		const durationSec = untrack(() =>
			"durationSec" in challenge.params ? challenge.params.durationSec : null
		);
		untrack(() => {
			initGame(startedOn);
			checkOutcome(startedOn);
		});

		window.addEventListener("keydown", handleKeydown);

		/** @type {ReturnType<typeof setInterval> | null} */
		let timer = null;
		if (timed && durationSec != null) {
			const durationMs = durationSec * 1000;
			timer = setInterval(() => {
				remainingMs = Math.max(0, durationMs - (Date.now() - startedOn));
				checkOutcome(startedOn);
			}, 200);
		}

		return () => {
			window.removeEventListener("keydown", handleKeydown);
			if (timer) clearInterval(timer);
		};
	});

	/** @type {import("@sveltejs/kit").SubmitFunction} */
	const onRetry = () => {
		retrying = true;
		return async ({ result: actionResult }) => {
			if (actionResult.type === "redirect") {
				await goto(actionResult.location);
				return;
			}
			retrying = false;
			await applyAction(actionResult);
		};
	};

	/**
	 * @param {unknown} value
	 * @returns {number | null}
	 */
	function asFiniteNumber(value) {
		return typeof value === "number" && Number.isFinite(value) ? value : null;
	}

	/** Stored metrics fallback for finished runs viewed after a reload (no live game). */
	const runMetrics = $derived(
		/** @type {{ moveCount?: unknown, mergeScore?: unknown, elapsedMs?: unknown }} */ (
			data.run.metrics ?? {}
		)
	);

	/** Stat cards for the result dialog, ranked metric first. */
	let resultStats = $derived.by(() => {
		const statMoves = game?.moveCount ?? asFiniteNumber(runMetrics.moveCount);
		const statScore = game?.score ?? asFiniteNumber(runMetrics.mergeScore);

		const moves = { label: "Moves", value: statMoves?.toLocaleString() ?? "—" };
		const score = { label: "Score", value: statScore?.toLocaleString() ?? "—" };
		const time = { label: "Time", value: formatChallengeElapsedMs(finishedElapsedMs) };

		if (isRecovery) return [moves, score, time];
		if (isTime) return [time, score, moves];
		return [score, moves, time];
	});
</script>

<svelte:head>
	<title>{challenge.title} - Play - 4096</title>
</svelte:head>

<form
	bind:this={completeForm}
	method="POST"
	action="?/complete"
	class="hidden"
	use:enhance={() => {
		return async ({ update }) => {
			await update({ reset: false });
			submitting = false;
		};
	}}
>
	<input type="hidden" name="runId" value={data.run.id} />
	<input
		type="hidden"
		name="status"
		value={result === "won" ? CHALLENGE_RUN_STATUS.WON : CHALLENGE_RUN_STATUS.LOST}
	/>
	<input
		type="hidden"
		name="score"
		value={isRecovery
			? (game?.moveCount ?? 0)
			: isTime
				? (finishedElapsedMs ?? Math.max(0, Date.now() - data.run.startedOn))
				: (game?.score ?? 0)}
	/>
	<input
		type="hidden"
		name="metrics"
		value={JSON.stringify({
			moveCount: game?.moveCount ?? 0,
			filledCells: game ? countFilledCells(game.board) : 0,
			elapsedMs: finishedElapsedMs ?? Math.max(0, Date.now() - data.run.startedOn),
			mergeScore: game?.score ?? 0,
		})}
	/>
</form>

<div
	class="challenge-play"
	ontouchstart={handleTouchStart}
	ontouchmove={handleTouchMove}
	ontouchend={handleTouchEnd}
>
	<div class="mb-3 flex items-start gap-2">
		<div class="flex-1">
			<p class="text-xs font-bold tracking-wide text-muted-foreground uppercase">Daily Challenge</p>
			<h1 class="text-2xl font-bold text-primary">{challenge.title}</h1>
			<p class="text-sm text-muted-foreground">{data.objective}</p>
		</div>
		<div class="flex gap-2">
			{#if isRecovery}
				<div
					class="min-w-[4.5rem] rounded-md px-3 py-2 text-center"
					style:background-color={page.data.theme?.boardBackground}
					style:color={page.data.theme?.textDark}
				>
					<div class="text-xs font-bold uppercase">Moves</div>
					<div class="font-bold">{game?.moveCount ?? 0}</div>
				</div>
				{#if winTile}
					<div
						class="min-w-[4.5rem] rounded-md px-3 py-2 text-center"
						style:background-color={page.data.theme?.boardBackground}
						style:color={page.data.theme?.textDark}
					>
						<div class="text-xs font-bold uppercase">Goal</div>
						<div class="font-bold">{winTile}</div>
					</div>
				{/if}
			{:else}
				<div
					class="min-w-[4.5rem] rounded-md px-3 py-2 text-center"
					style:background-color={page.data.theme?.boardBackground}
					style:color={page.data.theme?.textDark}
				>
					<div class="text-xs font-bold uppercase">Score</div>
					<div class="font-bold">{game?.score.toLocaleString() ?? "—"}</div>
				</div>
				{#if isTime}
					<div
						class="min-w-[4.5rem] rounded-md px-3 py-2 text-center"
						style:background-color={page.data.theme?.boardBackground}
						style:color={remainingMs <= 10000 ? "#b91c1c" : page.data.theme?.textDark}
					>
						<div class="text-xs font-bold uppercase">Time</div>
						<div class="font-bold">{formatTime(remainingMs)}</div>
					</div>
				{/if}
			{/if}
		</div>
	</div>

	{#if game}
		<AnimatedBoard {game} {pendingEvents} {popEvent} showControls={false} />
	{:else}
		<div
			class="mb-4 flex aspect-square items-center justify-center rounded-lg"
			style:background-color={page.data.theme?.boardBackground}
		>
			Loading…
		</div>
	{/if}

	<p class="text-center text-sm text-muted-foreground">
		Arrow keys or swipe to move. Challenge progress is saved when you finish.
	</p>

	<p class="mt-3 text-center text-sm">
		<a href="/challenges/{challenge.id}" class="text-primary hover:underline"> Abandon & back </a>
	</p>
</div>

{#if result}
	<div class="overlay">
		<div class="overlay-content">
			<h2>{result === "won" ? "Challenge Cleared!" : "Challenge Failed"}</h2>
			<p>
				{#if result === "won"}
					Nice work — {data.objective.toLowerCase()}.
				{:else if isTime}
					Time's up (or game over) before reaching the target score.
				{:else}
					Game over before the objective was met.
				{/if}
			</p>
			<GameStats stats={resultStats} label="Challenge stats" />
			<div class="flex flex-wrap justify-center gap-2">
				<form method="POST" action="?/start" use:enhance={onRetry}>
					<Button type="submit" class="justify-center" disabled={retrying || submitting}>
						{retrying ? "Starting…" : "Retry"}
					</Button>
				</form>
				<Button href="/challenges" class="justify-center" variant="secondary">Calendar</Button>
			</div>
		</div>
	</div>
{/if}

<style lang="postcss">
	.challenge-play {
		max-width: 500px;
		min-height: 100%;
		margin: 0 auto;
		padding: 20px;
		padding-bottom: 5rem;
		color: var(--foreground);
	}

	.overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.8);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
		padding: 1rem;
	}

	.overlay-content {
		background: var(--popover);
		padding: 2rem;
		border-radius: 12px;
		text-align: center;
		max-width: 400px;
		width: 100%;
		color: var(--popover-foreground);
	}

	.overlay-content h2 {
		margin: 0 0 0.75rem;
		font-size: 1.75rem;
	}

	.overlay-content p {
		margin: 0 0 0.5rem;
		font-size: 1.05rem;
	}
</style>
