// mobile/src/app/(app)/(tabs)/challenges.tsx
import { getChallenges } from "@/api/challenges";
import { Button } from "@/components/Button";
import { Icon } from "@/components/Icon";
import { Screen } from "@/components/Screen";
import {
  buildChallengeCalendar,
  CHALLENGE_RUN_STATUS,
  formatChallengeObjective,
  formatChallengeTypeLabel,
  parseChallengeDate
} from "@/game/challenges";
import { monthKey, shiftMonth } from "@/lib/format";
import { getInkColor } from "@/theme/themes";
import { useThemeStore } from "@/stores/theme";
import { useQuery } from "@tanstack/react-query";
import { Link, useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

const WEEKDAYS = ["S", "M", "T", "W", "T", "F", "S"];

export default function ChallengesScreen() {
  const theme = useThemeStore((s) => s.theme);
  const router = useRouter();
  const [month, setMonth] = useState<string | undefined>(undefined);
  const { data, isLoading, error } = useQuery({
    queryKey: ["challenges", month],
    queryFn: () => getChallenges(month)
  });

  const calendar = useMemo(() => {
    if (!data) return null;
    const parsed = parseChallengeDate(`${(month || data.month || data.today).slice(0, 7)}-01`);
    if (!parsed) return null;
    return buildChallengeCalendar({
      year: parsed.year,
      month: parsed.month,
      today: data.today,
      isPro: data.isPro,
      dayStatuses: data.dayStatuses
    });
  }, [data, month]);

  const todayCardBg = theme.challengeToday ?? theme.boardBackground;
  const todayInk = getInkColor(todayCardBg, theme);
  const boardInk = getInkColor(theme.boardBackground, theme);
  const todayParsed = data ? parseChallengeDate(data.today) : null;

  const goMonth = (delta: number) => {
    if (!calendar) return;
    const next = shiftMonth(calendar.year, calendar.month, delta);
    const key = monthKey(next.year, next.month);
    const todayKey = todayParsed ? monthKey(todayParsed.year, todayParsed.month) : key;
    if (delta > 0 && key > todayKey) return;
    setMonth(key);
  };

  const dayBackground = (status: string | null, isToday: boolean) => {
    if (status === CHALLENGE_RUN_STATUS.WON) return theme.challengeWon ?? "#059669";
    if (status === CHALLENGE_RUN_STATUS.LOST) return theme.challengeLost ?? "#9f1239";
    if (isToday) return theme.primary;
    return theme.boardBackground;
  };

  return (
    <Screen title="Daily Challenges" subtitle="A fresh challenge every midnight Central Time.">
      {isLoading ? <ActivityIndicator /> : null}
      {error ? <Text style={{ color: theme.destructive ?? theme.primary }}>Could not load challenges.</Text> : null}

      {data?.todayChallenge ? (
        <View style={[styles.today, { backgroundColor: todayCardBg }]}>
          <Text style={[styles.kicker, { color: todayInk }]}>Today · {data.today}</Text>
          <Text style={[styles.todayTitle, { color: todayInk }]}>{data.todayChallenge.title}</Text>
          <Text style={[styles.todayMeta, { color: todayInk }]}>
            {formatChallengeTypeLabel(data.todayChallenge.type)} · {data.todayChallenge.difficulty}
          </Text>
          <Text style={[styles.todayBody, { color: todayInk }]}>{formatChallengeObjective(data.todayChallenge)}</Text>
          <Link href={`/(app)/challenge/${data.todayChallenge.id}`} asChild>
            <Button>{data.isPro ? "Play today's challenge" : "View today's challenge"}</Button>
          </Link>
        </View>
      ) : null}

      {data && !data.isPro ? (
        <View style={[styles.upsell, { backgroundColor: theme.boardBackground }]}>
          <Text style={[styles.upsellText, { color: boardInk }]}>
            Browse today’s challenge below. Starting any challenge — and opening past days — requires Pro.
          </Text>
          <Link href="/(app)/pro" asChild>
            <Button>Upgrade to Pro</Button>
          </Link>
        </View>
      ) : null}

      {calendar ? (
        <View>
          <View style={styles.monthRow}>
            <Pressable accessibilityLabel="Previous month" onPress={() => goMonth(-1)} style={styles.monthBtn}>
              <Icon name="chevronLeft" color={theme.text ?? theme.textLight} />
            </Pressable>
            <Text style={[styles.monthLabel, { color: theme.text ?? theme.textLight }]}>{calendar.monthLabel}</Text>
            <Pressable
              accessibilityLabel="Next month"
              onPress={() => goMonth(1)}
              disabled={Boolean(todayParsed && monthKey(calendar.year, calendar.month) >= monthKey(todayParsed.year, todayParsed.month))}
              style={styles.monthBtn}
            >
              <Icon name="chevronRight" color={theme.text ?? theme.textLight} />
            </Pressable>
          </View>

          <View style={styles.weekRow}>
            {WEEKDAYS.map((label, i) => (
              <Text key={`${label}-${i}`} style={[styles.weekday, { color: theme.textLight }]}>
                {label}
              </Text>
            ))}
          </View>

          <View style={styles.grid}>
            {Array.from({ length: calendar.startWeekday }, (_, i) => (
              <View key={`blank-${i}`} style={styles.day} />
            ))}
            {calendar.days.map((day) => {
              if (day.isFuture) {
                return (
                  <View key={day.dateStr} style={[styles.day, styles.dayInner]}>
                    <Text style={{ color: theme.textLight, opacity: 0.5 }}>{day.day}</Text>
                  </View>
                );
              }
              const bg = day.locked ? theme.boardBackground : dayBackground(day.status, day.isToday);
              const ink = getInkColor(bg, theme);
              return (
                <Pressable
                  key={day.dateStr}
                  accessibilityLabel={`${day.dateStr}${day.isToday ? ", today" : ""}`}
                  onPress={() => router.push(day.locked ? "/(app)/pro" : `/(app)/challenge/${day.id}`)}
                  style={[
                    styles.day,
                    styles.dayInner,
                    { backgroundColor: bg },
                    day.isToday ? { borderWidth: 2, borderColor: theme.primary } : null
                  ]}
                >
                  <Text style={{ color: ink, fontWeight: "700" }}>{day.day}</Text>
                  {day.locked ? <Icon name="crown" size={11} color={ink} /> : null}
                  {day.status === CHALLENGE_RUN_STATUS.WON ? <Icon name="check" size={11} color={ink} /> : null}
                  {day.status === CHALLENGE_RUN_STATUS.LOST ? <Icon name="close" size={11} color={ink} /> : null}
                </Pressable>
              );
            })}
          </View>
        </View>
      ) : null}
    </Screen>
  );
}

const styles = StyleSheet.create({
  today: { borderRadius: 16, padding: 16, gap: 8 },
  kicker: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", opacity: 0.75 },
  todayTitle: { fontSize: 22, fontWeight: "900" },
  todayMeta: { fontSize: 13, opacity: 0.85 },
  todayBody: { fontSize: 14, marginBottom: 4 },
  upsell: { borderRadius: 12, padding: 16, gap: 10, alignItems: "center" },
  upsellText: { textAlign: "center", fontSize: 14 },
  monthRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  monthBtn: { padding: 8 },
  monthLabel: { fontSize: 18, fontWeight: "800" },
  weekRow: { flexDirection: "row" },
  weekday: { flex: 1, textAlign: "center", fontSize: 12, fontWeight: "800" },
  grid: { flexDirection: "row", flexWrap: "wrap" },
  day: { width: "14.285%", aspectRatio: 1, padding: 2 },
  dayInner: { borderRadius: 10, alignItems: "center", justifyContent: "center", gap: 1 }
});

// src/routes/challenges/+page.svelte
<script>
	import { page } from "$app/state";
	import Btn from "$lib/components/Btn.svelte";
	import { CHALLENGE_RUN_STATUS, formatChallengeTypeLabel } from "$lib/challenges.js";
	import { CrownIcon, ChevronLeftIcon, ChevronRightIcon } from "@lucide/svelte";

	let { data } = $props();

	const weekdays = ["S", "M", "T", "W", "T", "F", "S"];

	/**
	 * @param {string | null} status
	 */
	function statusClass(status) {
		if (status === CHALLENGE_RUN_STATUS.WON) return "won";
		if (status === CHALLENGE_RUN_STATUS.LOST) return "lost";
		if (status === CHALLENGE_RUN_STATUS.IN_PROGRESS) return "progress";
		return "";
	}

	/**
	 * Background for a calendar day cell. Status colors fill the whole day
	 * so cleared/failed days stay readable on the brand primary (today).
	 * @param {{ status: string | null; isToday: boolean }} day
	 */
	function dayBackground(day) {
		if (day.status === CHALLENGE_RUN_STATUS.WON) return "#16a34a";
		if (day.status === CHALLENGE_RUN_STATUS.LOST) return "#dc2626";
		if (day.isToday) return page.data.theme?.primary;
		return page.data.theme?.boardBackground;
	}

	/**
	 * @param {{ status: string | null; isToday: boolean }} day
	 */
	function dayColor(day) {
		if (day.status === CHALLENGE_RUN_STATUS.WON || day.status === CHALLENGE_RUN_STATUS.LOST) {
			return "#ffffff";
		}
		return page.data.theme?.textDark;
	}
</script>

<svelte:head>
	<title>Daily Challenges - 4096</title>
	<meta
		name="description"
		content="A new daily challenge every midnight Central Time. Pro unlocks the calendar archive."
	/>
</svelte:head>

<main
	class="mx-auto w-full max-w-lg px-4 pt-8 pb-28"
	style:color={page.data.theme?.text}
>
	<h1 class="text-3xl font-bold text-[var(--color-primary)]">Daily Challenges</h1>
	<p class="mb-5 text-sm text-gray-500">
		A fresh challenge every midnight Central Time ({data.timezone.replace("_", " ")}).
	</p>

	{#if data.todayChallenge}
		<section
			class="mb-6 rounded-xl p-4"
			style:background-color={page.data.theme?.boardBackground}
			style:color={page.data.theme?.textDark}
		>
			<p class="mb-1 text-xs font-bold tracking-wide uppercase opacity-70">Today · {data.today}</p>
			<h2 class="text-xl font-bold">{data.todayChallenge.title}</h2>
			<p class="mb-1 text-sm opacity-80">
				{formatChallengeTypeLabel(data.todayChallenge.type)} · {data.todayChallenge.difficulty}
			</p>
			<p class="mb-3 text-sm opacity-90">{data.todayChallenge.objective}</p>
			<Btn href="/challenges/{data.todayChallenge.id}" class="w-full justify-center">
				{data.isPro ? "Play today's challenge" : "View today's challenge"}
			</Btn>
		</section>
	{/if}

	{#if !data.isPro}
		<div
			class="mb-5 rounded-lg p-4 text-center"
			style:background-color={page.data.theme?.boardBackground}
		>
			<p class="mb-3 text-sm" style:color={page.data.theme?.textDark}>
				Browse today's challenge below. Starting any challenge — and opening past days — requires
				Pro.
			</p>
			<Btn href="/stripe" class="justify-center gap-2">
				<CrownIcon size={20} />
				Upgrade to Pro
			</Btn>
		</div>
	{/if}

	<section class="calendar">
		<div class="mb-3 flex items-center justify-between">
			<a
				href={data.calendar.prevHref}
				class="inline-flex rounded-md p-2 hover:opacity-80"
				style:background-color={page.data.theme?.boardBackground}
				aria-label="Previous month"
			>
				<ChevronLeftIcon size={20} />
			</a>
			<h2 class="text-lg font-bold">{data.calendar.monthLabel}</h2>
			{#if data.calendar.nextHref}
				<a
					href={data.calendar.nextHref}
					class="inline-flex rounded-md p-2 hover:opacity-80"
					style:background-color={page.data.theme?.boardBackground}
					aria-label="Next month"
				>
					<ChevronRightIcon size={20} />
				</a>
			{:else}
				<span class="inline-flex rounded-md p-2 opacity-30" aria-hidden="true">
					<ChevronRightIcon size={20} />
				</span>
			{/if}
		</div>

		<div
			class="weekday-row mb-1 grid grid-cols-7 gap-1 text-center text-xs font-bold text-gray-500"
		>
			{#each weekdays as label, i (i)}
				<span>{label}</span>
			{/each}
		</div>

		<div
			class="grid grid-cols-7 gap-1"
			style:grid-template-rows={`repeat(${Math.ceil((data.calendar.startWeekday + data.calendar.days.length) / 7)}, minmax(0, 1fr))`}
		>
			{#each Array.from({ length: data.calendar.startWeekday }, (_, i) => i) as blankIndex (blankIndex)}
				<span class="aspect-square"></span>
			{/each}

			{#each data.calendar.days as day (day.dateStr)}
				{#if day.isFuture}
					<span
						class="day future flex aspect-square flex-col items-center justify-center rounded-lg text-sm text-gray-400"
					>
						{day.day}
					</span>
				{:else if day.locked}
					<a
						href="/stripe"
						class="day locked flex aspect-square flex-col items-center justify-center rounded-lg text-sm"
						style:background-color={page.data.theme?.boardBackground}
						style:color={page.data.theme?.textDark}
						title="Pro unlocks past challenges"
					>
						<span class="font-semibold">{day.day}</span>
						<CrownIcon size={12} class="opacity-70" />
					</a>
				{:else}
					<a
						href="/challenges/{day.id}"
						class="day {statusClass(
							day.status
						)} flex aspect-square flex-col items-center justify-center rounded-lg text-sm font-semibold transition-opacity hover:opacity-90"
						class:today={day.isToday}
						style:background-color={dayBackground(day)}
						style:color={dayColor(day)}
						aria-label={`${day.dateStr}${day.status === CHALLENGE_RUN_STATUS.WON ? ", cleared" : day.status === CHALLENGE_RUN_STATUS.LOST ? ", failed" : ""}`}
					>
						<span>{day.day}</span>
					</a>
				{/if}
			{/each}
		</div>

		<div class="mt-4 flex flex-wrap gap-3 text-xs text-gray-500">
			<span class="inline-flex items-center gap-1.5">
				<span class="swatch won-swatch"></span> Cleared
			</span>
			<span class="inline-flex items-center gap-1.5">
				<span class="swatch lost-swatch"></span> Failed
			</span>
			{#if !data.isPro}
				<span class="inline-flex items-center gap-1">
					<CrownIcon size={12} /> Past days (Pro)
				</span>
			{/if}
		</div>
	</section>
</main>

<style>
	.swatch {
		width: 12px;
		height: 12px;
		border-radius: 4px;
		display: inline-block;
	}

	.won-swatch {
		background: #16a34a;
	}

	.lost-swatch {
		background: #dc2626;
	}

	.day.today {
		box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-primary) 55%, transparent);
	}
</style>
